# Generated by Django 3.1.7 on 2021-03-28 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100, verbose_name='Post title')),
                ('description', models.CharField(max_length=50, verbose_name='Post description')),
                ('content', models.TextField(max_length=300, verbose_name='Post content')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.EmailField(max_length=100, verbose_name='User email')),
            ],
            options={
                'db_table': 'table_users',
            },
        ),
    ]
