# Generated by Django 3.1.7 on 2021-04-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210405_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-id']},
        ),
    ]
