# Generated by Django 3.1.7 on 2021-04-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_logger_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='path',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
