# Generated by Django 3.1.7 on 2021-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_logger_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logger',
            name='utm',
            field=models.CharField(max_length=500),
        ),
    ]
