# Generated by Django 3.1.7 on 2021-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210411_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time_execution',
            field=models.DecimalField(decimal_places=47, max_digits=50),
        ),
    ]
