# Generated by Django 3.1.7 on 2021-04-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0019_auto_20210417_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books',
                                    to='main.category'),
        ),
    ]
